### ISSUE TITLE
Clean up configreader

### ISSUE THREAD

**Issue by richterjakob** [StanfordCBCL/svZeroDPlus#29]
As a prerequisite for #24, I wanted to clean up the configuration reading a bit by splitting the JSON handling from the actual config reading, as a lot of code redundancy resulted from that and the config reader got really messy.

On the way, I made a few other modifications that can be helpful:

* Fixed the Debug build of svZeroDSolver (no weird error anymore)
* DEBUG messages are automatically turned on for Debug builds (`-DCMAKE_BUILD_TYPE=Debug`) and turned of for Release builds (this would resolve #21)
* Fixed deprecation warning caused by `sprintf` by replacing it with `snprintf`
* Make use of `string_view` instead of `string` when feasible

Pull request: #27

**Comment by mrp089** [comment]
Awesome, thank you for your clean ups!
