### ISSUE TITLE
Community Standards

### ISSUE THREAD

**Issue by mrp089** [StanfordCBCL/svZeroDPlus#47]
I just stumbled upon [the Community Standards page](https://github.com/StanfordCBCL/svZeroDPlus/community) of this repository. There are some good ideas in there (which we already want to implement @MatteoSalvador, @alisonmarsden), with examples:
-  [Code of conduct](https://opensource.guide/code-of-conduct/)
- [Contributing](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) (in addition to the examples we have from [openCARP](https://opencarp.org/community/contribute) and [OpenFoam](https://cfd.direct/openfoam/management/sustainable-openfoam-development/))
- [Issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
- [Pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

We can start adding those to this repository and then adapt them for "larger" projects (like `svFSI+/-`).

**Comment by alisonmarsden** [comment]
Yes agreed - we can develop these here and then migrate to other projects.

**Comment by mrp089** [comment]
Closing this. Community standards will automatically be adopted once this repository moves to https://github.com/SimVascular (see https://github.com/SimVascular/simvascular.github.io/issues/8).
