### ISSUE TITLE
Make documentation consistent

### ISSUE THREAD

**Issue by menon-karthik** [StanfordCBCL/svZeroDPlus#58]
The documentation for the governing equations is inconsistent in terms of nomenclature and is also slightly different from the implemented equations in some places. This makes the documentation a little hard to use.

Just as an example, in the RCR boundary condition [documentation page](https://stanfordcbcl.github.io/svZeroDPlus/class_windkessel_b_c.html), we use $P_{ref}$ for the distal pressure, but it is `Pd` in the code; there are $Q^e$ and $P^e$ in the equations, but not in the schematic and the label $P_C$ is in the wrong place; the order of equations in the code is actually reversed. I'm assuming this is the case in many other places (for example, I haven't even bothered putting in the equations for `ClosedLoopHeartPulmonary`). 

We should go through and make sure things are consistent. Also, they might not be consistent with the [ROM simulation guide](https://simvascular.github.io/documentation/rom_simulation.html#0d-solver). 

Should we continue having the documentation in two places or can we get rid of the [ROM simulation guide](https://simvascular.github.io/documentation/rom_simulation.html#0d-solver) and just provide a link to this documentation since it's much more comprehensive and is also connected to code updates?

**Comment by mrp089** [comment]
Yes! With #53 we should have all the documentation from [simvascular.github.io](https://github.com/SimVascular/simvascular.github.io) in Doxygen. I'll delete the simvascular.github.io content and link to Doxygen.

Additionally, I'll go over the blocks and make sure the Doxygen matches with the code.

**Comment by menon-karthik** [comment]
Just so we don't forget to fix this as part of this issue: the documentation in [ROM simulation guide](https://simvascular.github.io/documentation/rom_simulation.html#0d-solver) has drifted further since the recent gen-α commit. The governing equations themselves (for example, the handling of non-linear terms) are different in the two places.

**Comment by menon-karthik** [comment]
There is still some block-specific documentation that is not consistent between the equations/figures in Doxygen and the actual equations implemented. I will look at that and clean up in the next couple of days.
