### ISSUE TITLE
Clean up code 

### ISSUE THREAD

**Issue by ktbolt** [StanfordCBCL/svZeroDPlus#59]
I will clean up the code a bit to follow best practices and such.

**Comment by menon-karthik** [comment]
@ktbolt Can you elaborate a little bit on the best practices you have in mind? Might be useful to have this documented somewhere for posterity.

**Comment by ktbolt** [comment]
@menon-karthik Some of these are stated in [Coding Guidlines](https://github.com/SimVascular/svFSIplus/blob/main/Documentation/pages/implementation.md) but most are C++ practices that _everybody_ knows.

I should create a Lab document for this with links to appropriate websites and such.

**Comment by ktbolt** [comment]
Note that developers will look at the  current code to see how things are done.

**Comment by mrp089** [comment]
@ktbolt, it would be great to add **your** C++ standards to https://github.com/SimVascular/.github on the off chance that _not everybody_ has the same ideas as you. The one you linked is very svFSI/FORTRAN specific.

Can you briefly say what you plan for `0D+` specifically?

**Comment by ktbolt** [comment]
@mrp089 These are not really my standards. 

C++ best practices have been developed over the years by the C++ community, Bjarne Stroustrup, Herb Sutter, Scott Meyers and others. 

I will try to produce a document that distills the essence of the C++ best practices.

**Comment by mrp089** [comment]
Cool!

Specifically for `0D+`, what are your plans?

**Comment by ktbolt** [comment]
I have no grand plan for the ZeroDSolver.  I will just go through the code and add/modify it as needed. 

However, a couple of things I have noticed when removing templates and testing
- Add error checking to applications `main` (svzerodsolver segfaults when given no arguments, input files are not checked if they exist, catch  nlohmann::json parse errors, etc.)
- Add error checking to `calibrate`
- Lots of empty constructors/destructors (maybe because of Eigen)
- Remove any magic numbers and literals (e.g. "F")
- Clean up any template residue

**Comment by ktbolt** [comment]
I've made several changes
- Added error checking to `svzerodcalibrator` and `svzerodsolver` `main` functions.
- Made `enum class BlockType` names more readable
   `closed_loop_coronary_lefT_bc` replaces `CLOSEDLOOPCORONARYLEFTBC`
- Replaced `unsigned int` with `int`
- Replaced `std::map<std::string, int> num_triplets` map with `TripletsContributions` struct
     `num_triplets.F` replaces `num_triplets["F"] `

**Comment by ktbolt** [comment]
I've made some more changes
- removed some empty constructions
- defined const functions where appropriate
- removed `this->` from vessel blocks 

This all I'm going to do for this Issue.

There are other specific parts of the implementation that I would like to improve like removing the heavy use for string literals in the code to identify parameters, types and such. I'll open separate Issues for those improvements.

**Comment by ktbolt** [comment]
Merge into `main`.
