### ISSUE TITLE
The LaTeX equations in the source documentation are not being rendered

### ISSUE THREAD

**Issue by ktbolt** [StanfordCBCL/svZeroDPlus#65]
When viewing source documentation from https://stanfordcbcl.github.io/svZeroDPlus the LaTeX equations are not being rendered.

For example, visiting https://stanfordcbcl.github.io/svZeroDPlus/class_blood_vessel.html#details I see

<img width="972" alt="Screen Shot 2023-11-06 at 9 58 59 AM" src="https://github.com/StanfordCBCL/svZeroDPlus/assets/23109458/23c629ad-cd23-411a-bf2a-7847e06ac350">

I have tested using Chrome, Safari and Edge, same problem.

**Comment by mrp089** [comment]
I'm going to revert the documentation to `USE_MATHJAX = NO`.
