### ISSUE TITLE
Add checking for a valid JSON to the svzerodsolver application

### ISSUE THREAD

**Issue by ktbolt** [StanfordCBCL/svZeroDPlus#70]
The `svzerodsolver` application does not appear to check if the input JSON file contains valid information. 

For example running `svzerodsolver`  with `steadyFlow_calibration.json` produces the confusing error message
```
libc++abi.dylib: terminating with uncaught exception of type nlohmann::json_abi_v3_11_2::detail::type_error: [json.exception.type_error.306] cannot use value() with number
```
I spent a good amount of time trying to figure out the cause of this error, thought the JSON file was corrupted or something.

Other examples 
- removing the `junctions` JSON element produces a segfault
- adding another `"boundary_conditions` JSON element produces a segfault
- removing the `vessels` JSON element produces `cannot use operator[] with a numeric argument with number`

We will need to add some checks in the solver code to identify these errors and throw an exception with a helpful message.

**Comment by mrp089** [comment]
@ktbolt, are you doing this? If not, do you have suggestions on where to check this?  There already are a few exceptions in `load_simulation_model`.

**Comment by ktbolt** [comment]
@mrp089 I was not planning on doing this, will be quite involved to fix I think.

The problem is that the data obtained from `nlohmann::json` it not checked.

For example
```
      model.add_block(BlockType::blood_vessel,
                      {model.add_parameter(vessel_values["R_poiseuille"]),
                       model.add_parameter(vessel_values.value("C", 0.0)),
                       model.add_parameter(vessel_values.value("L", 0.0)),
                       model.add_parameter(
                           vessel_values.value("stenosis_coefficient", 0.0))},
                      vessel_name);
```
does not check if `vessel_values["R_poiseuille"]` exists, need to have something like
```
      if (!vessel_values.contains("R_poiseuille")) {
        throw("Vessel is missing R_poiseuille element");
      }
```

**Comment by mrp089** [comment]
I see. We could have a wrapper around `nlohmann::json` with better checking?

**Comment by ktbolt** [comment]
A wrapper would be good, something to check and throw an exception with a useful message. 

The problem to avoid is cluttering up the code with a bunch of error checking mixed in with creating blocks. Breaking up the `load_simulation_model()` into smaller functions might avoid that.

**Comment by ktbolt** [comment]
@mrp089 The solver still crashes when the input JSON file has misspelled or missing data.

For example in `svZeroDPlus/tests/cases/steadyFlow_R_coronary.json` if `bc_values` is misspelled as `bc_value`
```
Assertion failed: (it != m_value.object->end()), function operator[], file svZeroDPlus/build/_deps/json-src/include/nlohmann/json.hpp, line 2135
```

or if `INFLOW` is misspelled in `boundary_conditions": { "inlet": "INFLOW" ,"outlet": "OUT" },`
```
Segmentation fault: 11  $exe $indir/${file}.json ${outdir}/${file}.csv
```
